default_platform(:ios)

platform :ios do
  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "Enter the version type or specific version\n(major, minor, patch or 1.0.0): ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if versionNum
      increment_version_number(
        version_number: versionNum
      )
    elsif version == 'major' || version == 'minor' || version == 'patch'
      increment_version_number(
        bump_type: version
      )
    else
      UI.user_error!('[ERROR] Wrong version!!!!!!')
    end
  end

  lane :version do |options|
    updateVersion(options)
    increment_build_number(xcodeproj: 'Runner.xcodeproj')
    end

#   lane :beta do |options|
#   increment_build_number(
#       build_number: latest_testflight_build_number + 1,
#       xcodeproj: "Runner.xcodeproj"
#       )
#   flutter_build_ios
#    build_app(
#     workspace: 'Runner.xcworkspace',
#     scheme: 'Runner',
#     clean: true,
#   )
#   upload_to_testflight()
#   end

  lane :beta_apple do
    puts latest_testflight_build_number + 1
    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "Runner.xcodeproj"
    )
    flutter_build_apple
    build_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
#       clean: true,
#       xargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight()
  end

  lane :beta_one do
    puts latest_testflight_build_number + 1
    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "Runner.xcodeproj"
    )
    flutter_build_one
#     enable_automatic_code_signing
    build_app(
        workspace: 'Runner.xcworkspace',
        scheme: 'Runner',
#         skip_codesigning:true,
#         export_options: {
#             signingStyle: "automatic",
#             teamID: "F6Z47FNTJZ"
#         }
    )
#     enable_automatic_code_signing
    upload_to_testflight()
  end

  lane :flutter_build_apple do
      sh("cd", "..")
      sh("flutter build ios --no-codesign --target lib/main_apple.dart --release")
   end

   lane :flutter_build_one do
      sh("cd", "..")
      sh("flutter build ios --no-codesign --target lib/main_one.dart --release")
   end
end