name: pet_mobile_social_flutter
description: pet_mobile_social_flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  go_router: ^9.0.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.8.3
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  bubble: ^1.2.1
  linkfy_text: ^1.1.5
  intl: ^0.18.0
  flutter_svg: ^2.0.6
  widget_mask: ^1.0.0+0
  fluttertoast: ^8.2.2
  flutter_switch: ^0.3.2
  flutter_riverpod: ^2.3.6
  dio: ^5.2.1
  riverpod_annotation: ^2.1.1


  # 이미지 선택 기능의 의존성 라이브러리
  insta_assets_crop: ^0.0.2 # custom package from image_crop
  fraction: ^5.0.0 # to show crop ratio in crop view
  provider: ^6.0.5 # match with wechat_assets_picker package
  extended_image: ^8.0.1 # match with wechat_assets_picker package
  photo_manager: ^2.6.0
  video_player: ^2.6.0
  image_picker: ^0.8.7+5
  flutter_form_builder: ^9.0.0
  rxdart: ^0.27.7
  flutter_social_textfield: ^0.1.2
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.0.15
  drift: ^2.9.0
  image_gallery_saver: ^2.0.2

  #Social Login
  kakao_flutter_sdk: ^1.4.3
  flutter_naver_login: ^1.8.0
  google_sign_in: ^6.1.4

  appspector: ^0.9.0

  #localization
  easy_localization: ^3.0.2

  #Utils
  get_it: ^7.6.0
  package_info_plus: ^4.0.2

  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/feed/image/
    - assets/image/feed/icon/
    - assets/image/feed/icon/large_size/
    - assets/image/feed/icon/small_size/
    - assets/image/camera/icon/
    - assets/image/etc/icon/large_size/
    - assets/image/etc/icon/small_size/
    - assets/image/header/icon/large_size/
    - assets/image/header/icon/small_size/
    - assets/image/message/icon/large_size/
    - assets/image/message/icon/small_size/
    - assets/image/mypage/icon/
    - assets/image/search/icon/
    - assets/image/toast/icon/
    - assets/image/feed_write/image/
    - assets/image/loginScreen/
    - assets/image/signUpScreen/
    - assets/image/common/
    - assets/translations/



  fonts:
    - family: pretendard
      fonts:
        - asset: assets/font/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/pretendard/Pretendard-Regular.otf
          weight: 400


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - image/a_dot_burr.jpeg
  #   - image/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
