name: pet_mobile_social_flutter
description: pet_mobile_social_flutter
publish_to: 'none'

version: 0.1.5+24
scripts:
  codegen: flutter pub run build_runner build

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  go_router: ^13.0.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.7.0
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  #  bubble: ^1.2.1
  linkfy_text: ^1.1.5
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  widget_mask: ^1.0.0+0
  fluttertoast: ^8.2.2
  flutter_switch: ^0.3.2
  flutter_riverpod: ^2.3.6
  dio: ^5.4.0
  riverpod_annotation: ^2.1.1


  # 이미지 선택 기능의 의존성 라이브러리
  insta_assets_crop: ^0.0.2 # custom package from image_crop
  fraction: ^5.0.0 # to show crop ratio in crop view
  provider: ^6.1.1 # match with wechat_assets_picker package
  extended_image: ^8.1.1 # match with wechat_assets_picker package
  #  photo_manager: ^2.8.1
  photo_manager: ^3.0.0-dev.2
  photo_manager_image_provider: ^2.1.0
  video_player: ^2.6.0
  image_picker: ^0.8.7+5
  flutter_form_builder: ^9.1.1
  rxdart: ^0.27.7
  flutter_social_textfield: ^0.1.2
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.0.15
  image_gallery_saver: ^2.0.2

  #Social Login
  kakao_flutter_sdk: ^1.4.3
  flutter_naver_login: ^1.8.0
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0

  appspector: ^0.9.0

  #localization
  easy_localization: ^3.0.3

  flutter_staggered_grid_view: ^0.6.2
  flutter_cache_manager: ^3.3.0
  #  flutter_markdown: ^0.6.15

  #Utils
  get_it: ^7.6.0
  package_info_plus: ^4.0.2

  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.5

  #WebView
  flutter_inappwebview: ^6.0.0-beta.23
  url_launcher: ^6.1.10

  #Firebase
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.4
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5

  #notification(push)
  flutter_local_notifications: ^14.1.1

  #permission
  permission_handler: ^11.1.0

  encrypt: ^5.0.1

  dio_smart_retry: ^5.0.0

  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.15


  #chat
  #  matrix: ^0.22.6
  flutter_slidable:
    git:
      url: https://github.com/engine-smkang-uxplus/flutter_slidable
  flutter_gen: ^5.3.1
  flutter_app_badger: ^1.5.0
  swipe_to_action: ^0.2.0
  collection: ^1.17.1
  detectable_text_field: ^2.1.0
  bubble:
    #    path: "/Users/engine-thirdnsov/Projects/uxp_Projects/Github_Fork/bubble"
    git:
      url: https://github.com/engine-smkang-uxplus/bubble
  flutter_spinkit: ^5.2.0
  scroll_to_index: ^3.0.1
  flutter_animate: ^4.2.0
  multi_trigger_autocomplete: ^1.0.0

  infinite_scroll_pagination: ^3.2.0
  group_button: ^5.3.2

  shared_preferences: ^2.2.0
  thumbor: ^1.0.4
  zoom_pinch_overlay: ^1.4.1+3
  lottie: ^2.6.0
  flutter_html: ^3.0.0-beta.2
  ua_client_hints: ^1.1.3
  firebase_remote_config: ^4.2.5
  cached_network_image: ^3.3.0
  app_install_date: ^0.1.2
  focus_detector: ^2.0.1
  cupertino_will_pop_scope: ^1.2.1
  geocoding: ^2.1.0
  just_the_tooltip: ^0.0.12
  table_calendar: ^3.0.9
  screenshot: ^2.1.0
  dropdown_button2: ^2.3.9
  pointycastle: ^3.7.3
  uuid: ^3.0.6
  channel_talk_flutter: ^2.4.0
  crypto: ^3.0.3
  asn1lib: ^1.5.0
  tosspayments_sdk_flutter: ^0.1.11
  uni_links: ^0.5.1
  numberpicker: ^2.1.2

  #  #네이버 지도
  #  flutter_naver_map: ^1.0.2
  #  flutter_bottom_drawer: ^0.0.7
  #  location: ^5.0.3
  #  flutter_background_service: ^5.0.2
  #  geolocator: ^10.1.0
  #  pedometer: ^4.0.1

  xml: ^6.3.0 # 버전 충돌로 이전 버전 사용
  #  xml_map_converter: ^1.0.0+1
  xml2json: ^6.2.0

  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  store_redirect: ^2.0.1
  vchatcloud_flutter_sdk:
    path: '../library/flutter_vchat_sdk'
  web_socket_channel: ^2.3.0

  custom_refresh_indicator: ^3.0.0

  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.3.7
  drift_dev: ^2.9.0
  analyzer: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/feed/image/
    - assets/image/feed/icon/
    - assets/image/feed/icon/large_size/
    - assets/image/feed/icon/small_size/
    - assets/image/camera/icon/
    - assets/image/etc/icon/large_size/
    - assets/image/etc/icon/small_size/
    - assets/image/header/icon/large_size/
    - assets/image/header/icon/small_size/
    - assets/image/message/icon/large_size/
    - assets/image/message/icon/small_size/
    - assets/image/my_page/icon/
    - assets/image/search/icon/
    - assets/image/toast/icon/
    - assets/image/feed_write/image/
    - assets/image/loginScreen/
    - assets/image/signUpScreen/
    - assets/image/common/
    - assets/image/logo/
    - assets/translations/
    - assets/image/chat/
    - assets/image/character/
    - assets/lottie/
    - assets/web/kakao_postcode.html



  fonts:
    - family: pretendard
      fonts:
        - asset: assets/font/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/pretendard/Pretendard-Regular.otf
          weight: 400
    - family: puppycat_social
      fonts:
        - asset: assets/font/icon_font/puppycat_social.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - image/a_dot_burr.jpeg
  #   - image/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
