name: pet_mobile_social_flutter
description: pet_mobile_social_flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  riverpod: ^2.3.6
  go_router: ^7.1.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.8.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  freezed: ^2.3.4

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/font/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/pretendard/Pretendard-Regular.otf
          weight: 400


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - image/a_dot_burr.jpeg
  #   - image/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
